title: Cloud Computing Applications
description: Cloud Computing Applications
template:
  repo: cloud-computing-applications-template
  name: cloud-computing-applications
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Introduction
    description: Introduction to cloud computing applications
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
